/*
 * framePrincipal.java
 *
 * Created on 17 de Março de 2009, 10:34
 */

package xadrezfinal;

import Tabuleiro.FabricaTabuleiro;
import Tabuleiro.Jpanel;
import Tabuleiro.TabuleiroXadrez;
import java.awt.Color;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.Timer;
import modelo.jogadores.*;


/**
 *
 * @author  Pedro
 */
public class FramePrincipal extends javax.swing.JFrame {

    
    protected TabuleiroXadrez tabuleiro;
    private EntradaJogo entrada;
    protected static int jogadorDaVez;
    protected ArrayList<Jogador> jogadores=new ArrayList<>();
    protected Jogada jogada;
    private boolean estrategico=false;
    private int currentSegundo = 0;
    private int currentMinuto = 0;
    private int currentHora = 0;
    private int velocidade = 1000;
    private Timer timer;
    
    /** Creates new form framePrincipal */
    public FramePrincipal() {
        initComponents();
        this.jogada=new Jogada();
        adicionaPanelEntrada();
        this.JMenuJogo.setEnabled(false);
        this.iniciarContagem();
        stopTime();
        //this.tabuleiro = tab;
        //this.jogada=jog;
        //this.jogadores=jogador;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblJjogador = new javax.swing.JLabel();
        lbMensagem = new javax.swing.JLabel();
        jToggleButtonUndo = new javax.swing.JToggleButton();
        jToggleButtonPause = new javax.swing.JToggleButton();
        jLabelCont = new javax.swing.JLabel();
        play = new javax.swing.JToggleButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        JMenuJogo = new javax.swing.JMenu();
        JMenuXadrez = new javax.swing.JMenu();
        JMenuXadrezBasico = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        JMenuSair = new javax.swing.JMenuItem();
        JMenuSobre = new javax.swing.JMenu();
        JMenuInformacoes = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblJjogador.setBackground(new java.awt.Color(255, 255, 204));
        lblJjogador.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblJjogador.setText("Jogador da vez :");

        lbMensagem.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbMensagem.setForeground(new java.awt.Color(255, 0, 0));
        lbMensagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jToggleButtonUndo.setText("Undo");
        jToggleButtonUndo.setEnabled(false);

        jToggleButtonPause.setText("PAUSAR");
        jToggleButtonPause.setEnabled(false);
        jToggleButtonPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonPauseActionPerformed(evt);
            }
        });

        jLabelCont.setText("00:00:00");

        play.setText("Play");
        play.setEnabled(false);
        play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playActionPerformed(evt);
            }
        });

        jMenuBar1.setEnabled(false);

        JMenuJogo.setLabel("Jogo");

        JMenuXadrez.setText("Xadrez");

        JMenuXadrezBasico.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        JMenuXadrezBasico.setText("Básico");
        JMenuXadrezBasico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuXadrezBasicoActionPerformed(evt);
            }
        });
        JMenuXadrez.add(JMenuXadrezBasico);

        jMenuItem1.setText("Estratégico");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        JMenuXadrez.add(jMenuItem1);

        JMenuJogo.add(JMenuXadrez);

        JMenuSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        JMenuSair.setText("Sair");
        JMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuSairActionPerformed(evt);
            }
        });
        JMenuJogo.add(JMenuSair);

        jMenuBar1.add(JMenuJogo);

        JMenuSobre.setText("Sobre");

        JMenuInformacoes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        JMenuInformacoes.setText("Informações");
        JMenuSobre.add(JMenuInformacoes);

        jMenuBar1.add(JMenuSobre);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblJjogador, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToggleButtonPause, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(play, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelCont)
                                .addGap(40, 40, 40)
                                .addComponent(jToggleButtonUndo)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(277, Short.MAX_VALUE)
                .addComponent(lblJjogador, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbMensagem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCont)
                            .addComponent(jToggleButtonUndo)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jToggleButtonPause)
                            .addComponent(play))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void JMenuXadrezBasicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuXadrezBasicoActionPerformed
    this.tabuleiro=new TabuleiroXadrez(this);
    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(this.tabuleiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(this.tabuleiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );

    pack();
        this.lblJjogador.setVisible(true);
        this.lblJjogador.setLocation(new Point(0,410));
        this.lblJjogador.setText(this.lblJjogador.getText()+" "+this.getJogadores().get(0).getNome());
        setJogadorDaVez(0);
        this.jToggleButtonUndo.setVisible(true);
        this.jToggleButtonPause.setVisible(true);
        this.play.setVisible(true);
        this.jLabelCont.setVisible(true);
        
        
        this.jToggleButtonUndo.setLocation(new Point(300,450));
        this.jToggleButtonUndo.setEnabled(true);
        this.jToggleButtonPause.setLocation(new Point(0,450));
        this.jToggleButtonPause.setEnabled(true);
        this.play.setLocation(new Point(100,450));
        this.play.setEnabled(true);
        this.jLabelCont.setLocation(new Point(200,450));
        this.timer.restart();
}//GEN-LAST:event_JMenuXadrezBasicoActionPerformed

private void JMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuSairActionPerformed
    this.dispose();
    System.exit(0);
}//GEN-LAST:event_JMenuSairActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        estrategico=true;
        this.tabuleiro=new TabuleiroXadrez(this);
    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(this.tabuleiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(this.tabuleiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );

    pack();
        this.lblJjogador.setVisible(true);
        this.lblJjogador.setLocation(new Point(0,410));
        this.lblJjogador.setText(this.lblJjogador.getText()+" "+this.getJogadores().get(0).getNome());
        setJogadorDaVez(0);
        this.getJogada().setJogador(getJogadores().get(0));
        
        this.jToggleButtonUndo.setVisible(true);
        this.jToggleButtonPause.setVisible(true);
        this.play.setVisible(true);
        this.jLabelCont.setVisible(true);
        
        
        this.jToggleButtonUndo.setLocation(new Point(300,450));
        this.jToggleButtonUndo.setEnabled(true);
        this.jToggleButtonPause.setLocation(new Point(0,450));
        this.jToggleButtonPause.setEnabled(true);
        this.play.setLocation(new Point(100,450));
        this.play.setEnabled(true);
        this.jLabelCont.setLocation(new Point(200,450));
        this.timer.restart();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jToggleButtonPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonPauseActionPerformed
        jToggleButtonPause.setEnabled(true);
        timer.stop();
        tabuleiro.desabilitaPecas();
    }//GEN-LAST:event_jToggleButtonPauseActionPerformed

    private void playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playActionPerformed
        play.setEnabled(true);
        timer.restart();
        tabuleiro.habilitaPecas();
    }//GEN-LAST:event_playActionPerformed

private void adicionaPanelEntrada(){
    entrada=new EntradaJogo(this);
    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(entrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(entrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

    pack();
    this.lblJjogador.setVisible(false);
    this.jToggleButtonUndo.setVisible(false);
    this.jToggleButtonPause.setVisible(false);
    this.play.setVisible(false);
    this.jLabelCont.setVisible(false);
    
}

public void habilitarMenu(){
    this.JMenuJogo.setEnabled(true);
}

public static int getJogadorDaVez() {
        return jogadorDaVez;
}

public static void setJogadorDaVez(int aJogadorDaVez) {
    jogadorDaVez = aJogadorDaVez;
}

public void setNovoJogador(Jogador jogador){
        this.getJogadores().add(jogador);
}
public Jogador getJogador(int indice){
    return this.getJogadores().get(indice);
}

  public Jogada getJogada() {
        return jogada;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JMenuInformacoes;
    private javax.swing.JMenu JMenuJogo;
    private javax.swing.JMenuItem JMenuSair;
    private javax.swing.JMenu JMenuSobre;
    private javax.swing.JMenu JMenuXadrez;
    private javax.swing.JMenuItem JMenuXadrezBasico;
    private javax.swing.JLabel jLabelCont;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JToggleButton jToggleButtonPause;
    private javax.swing.JToggleButton jToggleButtonUndo;
    private javax.swing.JLabel lbMensagem;
    private javax.swing.JLabel lblJjogador;
    private javax.swing.JToggleButton play;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JToggleButton getBotao() {
        return jToggleButtonPause;
    }

    public void setBotao(javax.swing.JToggleButton botao) {
        this.jToggleButtonPause = botao;
    }
    public ArrayList<Jogador> getJogadores() {
        return jogadores;
    }

    public void setJogadores(ArrayList<Jogador> jogadores) {
        this.jogadores = jogadores;
    }
    
    public void trocaJogador(){
        this.lblJjogador.setText("Jogador da vez: "+this.getJogada().getJogador().getNome());
    }
    
    public void terminarJogo(){
        this.lblJjogador.setForeground(new Color(255,255,255));
        this.lblJjogador.setBackground(new Color(255,0,0));
        this.lblJjogador.setOpaque(true);
        if(getJogadorDaVez()==0){
            this.lblJjogador.setText("O vencedor é: "+this.getJogadores().get(1).getNome());
        }else{
            this.lblJjogador.setText("O vencedor é: "+this.getJogadores().get(0).getNome());
        }
        
    }
    
    public void setEstrategico (boolean valor){
        this.estrategico=valor;
        }
    public boolean getEstrategico (){    
        return estrategico;
       }
    
    public void settimer (Timer time2){
        this.timer=time2;
        }
    public Timer gettimer (){    
        return timer;
       }

    private void iniciarContagem() {
        ActionListener action = new ActionListener() {  
            public void actionPerformed(ActionEvent e) {  
                currentSegundo++;
                
                if(currentSegundo==60){
                    currentMinuto++;
                    currentSegundo = 0;
                }
                
                if(currentMinuto==60){
                    currentHora++;
                    currentMinuto = 0;
                }
                
                String hr = currentHora <= 9? "0"+currentHora:currentHora+"";
                String min = currentMinuto <= 9? "0"+currentMinuto:currentMinuto+"";
                String seg = currentSegundo <= 9? "0"+currentSegundo:currentSegundo+"";
                
                jLabelCont.setText(hr+":"+min+":"+seg);  
            }  
        };  
        this.timer = new Timer(velocidade, action);  
        this.timer.start();
    }
    
    private void stopTime() {
        timer.stop();
        currentHora = 0;
        currentMinuto = 0;
        currentSegundo = 0;
        jLabelCont.setText("00:00:00");
    }

}
